spring.application.name=todo-rest

spring.datasource.url=jdbc:mysql://localhost:3306/todo_rest_daw?useSSL=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=false
server.port=${PORT:8080}